payments/urls.py
from django.urls import path
from payments.views import (
    TopUpView, 
    SuccessView, 
    CancelView, 
    WebhookView, 
    GetInvoiceView
)

app_name = 'payments'

urlpatterns = [
    path('top-up/', TopUpView.as_view(), name='top_up'),    
    path('success/', SuccessView.as_view(), name='success'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('webhooks/stripe/', WebhookView.as_view(), name='stripe-webhook'),
    path('invoice/<int:invoice_pk>', GetInvoiceView.as_view(), name='invoice_pdf'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('users/', include('users.urls', namespace='users')),
]

store/urls.py
from django.urls import path

from .views import HomepageView

app_name = 'store'

urlpatterns = [
    path('', HomepageView.as_view(), name='homepage'),
]

users/urls.py
from django.urls import path

from .views import CustomLoginView, CustomLogoutView

app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
]

store/models.py
from django.db import models

# Create your models here.

store/views.py
from django.conf import settings
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.


class HomepageView(TemplateView):
    template_name = 'store/about-me.html'

store/templates/store/about-me.html
{% extends 'store/base.html' %}
{% block content %}

    <div class="content-section">

        <h1 class="text-info">Hi! Welcome to my demo website.</h1>

        <p class="text-dark">This project mostly resolves around payment processing using 3rd party payment processor and dynamic invoicing.</p>
        <h5 class="text-info">Key technologies used are:</h5>
        <ul>
            <li class="text-dark">It is set up using Django framework. Since Django comes with so called 
                'batteries included', I am focusing on using many solutions provided by Django, for instance Generic Views, 
                overwritting their functions if necessary.</li>
            <li class="text-dark">It's frontend is based on HTML and Bootstrap.</li>
            <li class="text-dark">There is a bit of JavaScript involved, but not much since I focused on ensuring that 
                the website doesn't lose functionality when users turn it off - for example to manipulate required fields in forms.</li>
            <li class="text-dark">Speaking of forms, I used ModelForm and customized it with 
                <a href="https://django-crispy-forms.readthedocs.io/en/stable/" target="_blank" class="text-info">Django Crispy Forms</a> here.</li>
            <li class="text-dark">This project includes communication with API of popular 3rd party payment processor - <a href="https://stripe.com/docs/api" target="_blank" class="text-info">Stripe</a>.</li>
            <li class="text-dark">JSONs provided to Stripe to open up a payment checkout session are serialized using 
                <a href="https://marshmallow.readthedocs.io/en/stable/" target="_blank" class="text-info">Marshmallow</a>.</li>
            <li class="text-dark">Invoices for payments are dynamically generated using <a href="https://weasyprint.org/" target="_blank" class="text-info">Weasyprint</a>.</li>
        </ul>

        <h5 class="text-info">Now that this is out of the way, let me explain what can you do here.</h5>
        <p class="text-dark">This is the only page that you can access as an anonymous user. 
            Please <a href="https://docs.djangoproject.com/en/4.0/topics/auth/default/#creating-users" target="_blank" class="text-info">create user</a> 
            in your console and <a href="{% url 'users:login' %}" target="_blank" class="text-info">log in</a> to explore functionalities of this website.</p>
        <p class="text-dark">To explore functionalities, you must create a <a href="https://stripe.com" target="_blank" class="text-info">Stripe</a> account. 
            Make sure your <a href="https://dashboard.stripe.com/test/apikeys" target="_blank" class="text-info">Stripe test keys</a> and 
            <a href="https://stripe.com/docs/webhooks" target="_blank" class="text-info">Webhook key</a> are in .env file (you may have to restart the server if you're adding them now), and that you are 
            <a href="https://stripe.com/docs/stripe-cli/webhooks#forward-events" target="_blank" class="text-info">listening for events</a>
             - it's very important, because otherwise your balance will not increase after payment and the invoice won't be created. When using Stripe CLI use the following command:
             <p><i>stripe listen --forward-to localhost:8000/payments/webhooks/stripe/</i></p>
            <p>If everything looks good, you can <a href="{% url 'payments:top_up' %}" target="_blank" class="text-info">top up your account</a>.</p> 
        <p class="text-dark">If this is the first time you're providing data for invoice, you will be prompted to provide your name and address. 
            After that you will always have a choice: use again the most recent address associated with your account or provide a new one.</p>
        <p class="text-dark">To perform a successfull card payment, use card number
            <strong>4242 4242 4242 4242</strong>, valid until any date in the future, and with any 3 digits as its CVC code. 
            There are many more available test scenarios - more about that 
            <a href="https://stripe.com/docs/testing" target="_blank" class="text-info">here</a>.</p>
        <p class="text-dark">It's possible to use other payment options, for example Przelewy24, including popular Blik, 
            but that is subject to the settings of your Stripe account. This project is adapted to process Przelewy24 payments correctly. 
            You can turn it on <a href="https://dashboard.stripe.com/settings/payment_methods" target="_blank" class="text-info">here</a>. 
            Once it's set on, you will be able to choose it as payment option on checkout.</p> 
        <p class="text-dark">The entire time, webhook page is listening to JSONs sent from Stripe. Following a succeful payment, webhook will 
            capture confirmation of funds being available in your Stripe account and perform series of actions, like increasing your 
            wallet funds and sending you an e-mail with autogenerated invoice. 
            Mail backend is set for console, so please look out for it there. Invoices are autonumerated, restarting each month.</p>
        <p class="text=dark">Since invoice attached to the e-mail is a bytes object and can't be easily verified there, 
            it can be accessed through the <a href="/admin/" target="_blank" class="text-info">admin panel</a>, either in the 
            <a href="/admin/payments/invoice/" target="_blank" class="text-info">invoice</a> or the 
            <a href="/admin/payments/topup/" target="_blank" class="text-info">top up</a> model. 
            Of course you must be logged in as a <a href="https://docs.djangoproject.com/en/4.0/topics/auth/default/#creating-superusers" target="_blank" class="text-info">superuser</a> first.</p>
        <p class="text-dark">Since you are already there, feel free to download a selection of data about successful purchases as CSV file. It could be proven useful for accounting or statistics.
            It's an action available in the admin of <a href="/admin/payments/invoice/" target="_blank" class="text-info">invoice</a> model.</p>
        <p class="text-dark">For now you cannot spend money here in any way.</p>

        <h5 class="text-info">What next?</h5>

        <p class="text-dark">This project still has a lot of room for improvement and further development. Below is a list of some things that I plan to add here in the future:</p>
        <ul>
            <li class="text-dark">Make e-mail sending an asynchronous task to ensure it gets sent everytime.</li>
            <li class="text-dark">Add history of transactions.</li>
            <li class="text-dark">Add promotions functionality.</li>
            <li class="text-dark">Add more user functionalities - add a create account and update account views and remind password functionalities.</li>
            <li class="text-dark">Write tests, especially focusing on all kinds of scenarios for payments.</li>
            <li class="text-dark"><strong>Figure out what to sell here and then set it up.</strong></li>
        </ul>

        <p class="text-dark"></p>
        <h6 class="text-info">That pretty much wraps it up. Thank you for your time!</h6>
    </div>

{% endblock content %}

store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'store/base.css' %}">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <title> My demo </title>   
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
            <a class="navbar-brand" href="{% url 'store:homepage' %}">My Demo Shop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link text-light" href="{% url 'store:homepage' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-light" href="{% url 'payments:top_up' %}">Top up</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#">Shop</a>
                </li>
              </ul>
              <ul class="navbar-nav">
                {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link disabled text-light" href="#">{{ user.username }} : {{user.money_full_units }} zł</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'users:logout' %}">Logout</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'users:login' %}">Login</a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </nav>
      </header>

    <div class="container p-5">
      {% block content %}
      {% endblock %}
    </div>

    <footer class="footer mt-auto py-3 bg-info">
      <div class="container">
        <span id='author'>by <a href="https://github.com/lemarta"><i class="fa-brands fa-github"></i> lemarta</a>, 2022</span>
      </div>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>